name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Restart docker
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Restart docker
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: restart-docker
        with:
          command: 'docker compose down && docker compose up -d'